NordicPlayground/IOS-Common-Libraries

Sources/iOS-Common-Libraries/Extensions/Color/Color.swift, Sources/iOS-Common-Libraries/Extensions/Color/NSColor.swift, Sources/iOS-Common-Libraries/Extensions/Color/RGB.swift, Sources/iOS-Common-Libraries/Extensions/Color/RGBA.swift, Sources/iOS-Common-Libraries/Extensions/Color/UIColor.swift
Small changes here & there, but logic is mostly the same.
=> RGB (Color) Additions from Nick's code

README.md, Sources/iOS-Common-Libraries/Utilities/BitField.swift, Sources/iOS-Common-Libraries/Utilities/Option.swift
This has been in use for years by nRF Connect for Mobile.
=> Added BitField to the Library

Sources/iOS-Common-Libraries/Utilities/Cache.swift
=> Fix: Cache's init() was not public

README.md, Sources/iOS-Common-Libraries/Utilities/Data.swift
More code used by nRF Connect for Mobile, that we ourselves can use in our own apps. As well as you.
=> Added Byte-handling functions to Data Extension

README.md
This way whomever encounters this library can find a source of safety in using snippets or full code from it.
=> Added listing of Nordic apps using code from this library

Sources/iOS-Common-Libraries/Utilities/RSSI.swift, Sources/iOS-Common-Libraries/Views/RSSI/RSSIShape.swift, Sources/iOS-Common-Libraries/Views/RSSI/RSSIView.swift
This is also the same one used by nRF Connect, so we can patch that internally as well.
=> Added RSSI Logic from nRF Wi-Fi Provisioner

Sources/iOS-Common-Libraries/Utilities/RSSI.swift
This is what happens when you use your own stuff - you find issues :)
=> Public RSSI Enum Properties

Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
=> Fix: NordicLog's initialisers were not Public

Sources/iOS-Common-Libraries/Utilities/Sequence.swift
A bit of secret sauce from nRF Connect's source code.
=> Added Sequence KeyPath Utility APIs

Sources/iOS-Common-Libraries/Utilities/Sequence.swift
Don't say anything. There's no need.
=> Fix: Made KeyPath Utility APIs Public on Sequence

README.md, Sources/iOS-Common-Libraries/Utilities/View.swift
Another use case of an API we're going to use from multiple apps. Tried & tested in nRF Connect for Mobile.
=> View onceOnly API and README Update

Sources/iOS-Common-Libraries/Extensions/Optional.swift, Sources/iOS-Common-Libraries/Extensions/View.swift, Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift, Sources/iOS-Common-Libraries/Views/InlinePicker.swift
Yup, all of this is nRF Connect code.
=> Added InlinePicker from nRF Connect

Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
This is why it's always good to use your own stuff.
=> Fix: Public Accented Content Style

Sources/iOS-Common-Libraries/Views/InlinePicker.swift
Hopefully this is the last one.
=> Fix: Inline's init() was not public

Sources/iOS-Common-Libraries/Views/InlinePicker.swift
This makes it easier to use this API.
=> Added a helper init() for InlinePicker types that support CaseIterable

Sources/iOS-Common-Libraries/Views/InlinePicker.swift
Can't believe we didn't consider this earlier...
=> InlinePicker now supports 'systemImage'

Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
=> Update to AccentedLabelContentStyle to set accent color

Sources/iOS-Common-Libraries/Extensions/View.swift
Another bit of magic stolen from nRF Connect for Mobile / iOS treasure trove.
=> Added View extension helper to 'center' a UI Element

Sources/iOS-Common-Libraries/Utilities/SwiftUI/ViewModifiers.swift, Sources/iOS-Common-Libraries/Views/PasswordField.swift
I'm sure this is going to receive changes.
=> Ported nRF Edge Impulse's Password Field onto Common-Library

Sources/iOS-Common-Libraries/Views/PasswordField.swift
Since we need to use this, we make it a better component.
=> Further PassworldField Improvements

Sources/iOS-Common-Libraries/Views/IndeterminateProgressView.swift
And now, this is needed by Edge Impulse...
=> Added IndeterminateProgressView from Wi-Fi Prov App

Sources/iOS-Common-Libraries/Utilities/Array.swift, Sources/iOS-Common-Libraries/Views/Pipeline/PipelineManager.swift, Sources/iOS-Common-Libraries/Views/Pipeline/PipelineStage.swift
The issue here, is that in nRF Wi-Fi Provisioner we never set a progress value. But Edge Impulse does, so we found out this doesn't work. So now we need to implement it.
=> Changes to support Progress in PipelineManager

Sources/iOS-Common-Libraries/Utilities/Array.swift, Sources/iOS-Common-Libraries/Views/Pipeline/PipelineStage.swift
Two minor changes that could mean the difference between something not working and something working :)
=> API Pipeline Fixes

Sources/iOS-Common-Libraries/Extensions/Color/Color.swift, Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
And, is there no need now for the adapting color schemes?
=> Color now has System-defined Label Colors, so we can now make use of them

Sources/iOS-Common-Libraries/Utilities/SwiftUI/TextFieldAlertModifier.swift
This is from nRF Edge Impulse.
=> Added TextFieldAlertModifier

Sources/iOS-Common-Libraries/Utilities/SwiftUI/TextFieldAlertModifier.swift
As usual, we forgot to do this.
=> Marked TextFieldAlertModifier as Public

Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
Just trying to make what the class is, and its pointer, visible. To be able to discern memory leaks better.
=> Another turn to improve logs

Sources/iOS-Common-Libraries/Views/FPSCounter.swift
I knew something would catch me again...
=> Public Init for FPSCounter

Sources/iOS-Common-Libraries/Utilities/Collection.swift
More borrowed code from nRF Connect but, code that sometimes we miss. Many times, in fact.
=> Added Collection Extension

Sources/iOS-Common-Libraries/Views/IndeterminateProgressView.swift
It was not moving anymore across the entire width.
=> Fix for IndeterminateProgressView only moving on one side

Sources/iOS-Common-Libraries/Utilities/RSSI.swift
=> Added @practicalRange to RSSI

Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
I think this might be the start of many such changes. But hey, that's what libraries and using your own stuff is for.
=> Fix for NordicLog Import on macOS-only project

Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
I think this will be the last commit.
=> Hide UIView for Mac

Sources/iOS-Common-Libraries/Effects/Modifiers/FlickerModifier.swift, Sources/iOS-Common-Libraries/Effects/Shaders/Flicker.metal
=> Ported nRF Connect's "Flicker" shader

Sources/iOS-Common-Libraries/Parsers/HeartRateMeasurement.swift
The nRF Connect version is more complex, and supports more of the Data provided, even if we don't needed. But one implementation is better than two.
=> Ported nRF Connect's Heart Rate Measurement into iOS-Common-Library

Sources/iOS-Common-Libraries/Parsers/HeartRateMeasurement.swift
=> Minimal HeartRateMeasurementUnit Change

Sources/iOS-Common-Libraries/Utilities/Constant.swift
=> Added "bundleName" API to Constant

Sources/iOS-Common-Libraries/Views/NoContentView.swift
=> Added "NoContentView" from upcoming nRF Toolbox

Sources/iOS-Common-Libraries/Views/NoContentView.swift
Mostly because nRF Connect could use it.
=> Added a convenience initialiser to NoContentView

Sources/iOS-Common-Libraries/Utilities/Data.swift, Sources/iOS-Common-Libraries/Utilities/String.swift
It's now much closer to the more complete iOSMcuMgr version.
=> hexEncodedString() Update

Sources/iOS-Common-Libraries/Utilities/Float.swift
We're going to put more byte-parsing code into iOS-Common-Lib.
=> Added ReservedFloatValues

Sources/iOS-Common-Libraries/Utilities/Float.swift
So we don't need to have this code duplicate in both nRF Connect, nRF Toolbox, etc.
=> Added init(SFloat: Data)

Sources/iOS-Common-Libraries/Extensions/View.swift
=> Ported View's taskOnce {} from nRF Connect

Sources/iOS-Common-Libraries/Utilities/Date.swift
To the best of my current knowledge, I tried to implement the TimeZone and DST Offset Data that CGMS Session Start Time requires. Hopefully it's more useful in other situations.
=> Extended Data API to help with CGMS

Sources/iOS-Common-Libraries/Views/BadgeView.swift
This is all Nick's work. I'm just planning to use it more.
=> Ported nRF Toolbox's "ServiceBadge" now called BadgeView

Sources/iOS-Common-Libraries/Views/BadgeView.swift
=> Public BadgeView

Sources/iOS-Common-Libraries/Views/DotView.swift
There was already a second use of it in nRF Toolbox. So already duplicating the code was making me think of making a View. So here we are.
=> Added "DotView"

Sources/iOS-Common-Libraries/Utilities/Data.swift
Re-discovered this code that wasn't being used. But we're using it again, so it makes sense to move into common.
=> Added "Compression" and "sizeString" from nRF Connect

README.md
It should be noted there. If only so that I myself can remember it exists and that it's very useful code to have.
=> Added 'Compression' to README

README.md, Sources/iOS-Common-Libraries/Extensions/CGSize.swift
It only adds an init, but it's one that we use so much across all of our projects...
=> CGSize Extension

Sources/iOS-Common-Libraries/Extensions/View.swift
This is code that's been in nRF Connect for a while. Like, at least 2 years. Easy.
=> Stole nRF Connect's "fix" for DisclosureGroup

Sources/iOS-Common-Libraries/Views/CancellableTextField.swift
I didn't even remember we wrote this! I found it trying to copy something else from nRF Connect, and noticed the TextField looked custom and also very good. To my surprise, of course. But of course, most of it is copied, or based on a copy from the web. No AI.
=> Ported "CancellableTextField" from nRF-Connect

Sources/iOS-Common-Libraries/Views/CancellableTextField.swift
I mean it exists, but only for iOS.
=> Fixed Build Issue due to inexistent Color

Sources/iOS-Common-Libraries/Views/NoContentView.swift
Also inspired by Filip. Of course.
=> Small NoContentView Change

Sources/iOS-Common-Libraries/Parsers/CommonDataParser.swift, Sources/iOS-Common-Libraries/Parsers/NordicDataParser.swift
There's a new "dataSizeRequirement", which simplifies the work of extending and adopting the Parsers as an API, I feel like. Makes it a cool API to use, I think.
=> Update of NordicDataParser API

Sources/iOS-Common-Libraries/Parsers/NordicDataParser.swift
=> Added "greaterThan" Accepted DataFormat Byte count

Sources/iOS-Common-Libraries/Utilities/Data.swift
We were trying not to keep pulling so much. But this one as well is needed.
=> Ported nRF Connect's version of Data initialiser from hexString

Sources/iOS-Common-Libraries/Views/NordicDataField.swift
=> Fix for Internal NordicDataField init

Sources/iOS-Common-Libraries/Parsers/GlucoseMeasurement.swift
=> Marked reserveDescription() static functions as Public

Sources/iOS-Common-Libraries/Parsers/GlucoseMeasurement.swift
=> Completed GLS "GlucoseMeasurement" Implementation from GLS

Sources/iOS-Common-Libraries/Parsers/GlucoseMeasurement.swift
Some byte-fiddling over there that was incorrect. Or bit-fiddling?
=> Bug Fix: Parsing of Glucose Measurement Location

Sources/iOS-Common-Libraries/Parsers/GlucoseMeasurement.swift
There were a couple of values missing, leading to incorrect value parsing.
=> Fix for Glucose Sensor Type & Location

Sources/iOS-Common-Libraries/Views/NoContentView.swift
We missed this from last year! Why weren't we using them until now!?? Probably because we have too many things going on. But it's never too late!
=> Updated NoContentView with Symbol Effects

Sources/iOS-Common-Libraries/Parsers/Glucose/RecordOpcode.swift, Sources/iOS-Common-Libraries/Parsers/Glucose/RecordOperator.swift
I think we don't need to port more types for now. This is just to better parse / process RACP responses when sending requests for records.
=> Added (Glucose) RACP Record Operators

Sources/iOS-Common-Libraries/Parsers/Glucose/RecordResponseStatus.swift
This was missing. Hidden again in nRF Connect. But reusable.
=> Added RecordResponseStatus

Sources/iOS-Common-Libraries/Parsers/TemperatureMeasurement.swift
Using MeasurementFormatter() to show a measurement as a String does the right thing. We don't need a specific API for this.
=> Updated TemperatureMeasurement

Sources/iOS-Common-Libraries/Parsers/HeartRate/HeartRateMeasurement.swift, Sources/iOS-Common-Libraries/Parsers/HeartRate/HeartRateSensorContact.swift, Sources/iOS-Common-Libraries/Parsers/HeartRate/HeartRateSensorLocation.swift
This was missing! Because of course, everything needs its own variation of sensor location!
=> Added Heart Rate Sensor Location

Sources/iOS-Common-Libraries/Parsers/HeartRate/HeartRateMeasurement.swift
Imagine offset == 2 and data.count == 4.
=> Fix data parsing at the end of the array
