- Sources/iOS-Common-Libraries/Views/AppIconView.swift
Mac Catalyst is not 'OSX'. Because we don't get the same APIs, but a mixture of what was allowed or implemented as UIKit on macOS. Weird stuff I know.
> Proposed Fix for AppIconView to work on Mac Catalyst

- Sources/iOS-Common-Libraries/Utilities/BitField.swift
Sacrilege! But that's the good thing about making an API that you use Public, and then using it. You can test that it works or, compiles, as it should!
> Fix: BitField's all() static function was not made Public

- README.md
- Sources/iOS-Common-Libraries/Utilities/Cache.swift
If it's not public, we can't use it! Also, it was missing two functions that nRF Connect uses.
> Made Cache Utility Public

- Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
So the delegate, regardless of what was given, was always nil.
> NordicLog Class Initialiser did not pass-on delegate

- Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabelStyle.swift
It still baffles me that this API or something like it is not available out of the box in SwiftUI.
> Added ColorIconOnlyLabelStyle

- Sources/iOS-Common-Libraries/Utilities/SwiftUI/ViewModifiers.swift
- Sources/iOS-Common-Libraries/Views/PasswordField.swift
I understand why init is not made public by default if the type is public. But doesn't it lend to these kinds of situations all the time...
> Missing Public Initializers

- Sources/iOS-Common-Libraries/Views/Pipeline/PipelineView.swift
This is a provision for Edge Impulse app, which does need this.
> PipelineView now supports an extra 1-line Accessory Line

- Sources/iOS-Common-Libraries/Views/Pipeline/PipelineView.swift
We only want to show it when we're in progress, and without errors.
> Fix for PipelineView accessory line

- Sources/iOS-Common-Libraries/Views/Pipeline/PipelineView.swift
Otherwise long longs would destroy the UI.
> Limited Pipeline log lines to 1

- README.md
It's now easier to understand / see the components because the images don't take the full width of the Readme page.
> Corrected Readme Image Widths

- Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
- Sources/iOS-Common-Libraries/Views/InlinePicker.swift
Because the color we're setting is to the content of the "Label", not the Label itself. I know, it's confusing.
> Accented Labeled Style is now "Accented Content"

- Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
Yeah, what a tongue-twister. But basically, we set an accent color here for the 'Label' part of the content, and not to the content part of the content.
> Added 'AccentedLabel' Labeled Style

- Sources/iOS-Common-Libraries/Views/InlinePicker.swift
Until now, the content style was set to Accented Content. Now, it's not set.
> Change: InlinePicker no longer sets a default content style

- Sources/iOS-Common-Libraries/Utilities/SwiftUI/LabeledContentStyle.swift
The type names are far too similar...
> Fix for Accented Label Return

- Sources/iOS-Common-Libraries/Extensions/View.swift
Documentation states to not use the initialiser directly, and to instead use the .stack static variable. I did not find this, instead it came through this StackOverflow link: https://stackoverflow.com/questions/65316497/swiftui-navigationview-navigationbartitle-layoutconstraints-issue
> Fix for bad StackNavigationViewStyle init

- Sources/iOS-Common-Libraries/Extensions/UIView.swift
I tried to add some documentation as well. I wrote this for nRF Connect, but then thought it was "open" enough to be added to the common library. I don't think it'll be used much since modern apps now just rely on SwiftUI to handle the magic for events such as rotation, resizing and so on. This is where this helper is needed for nRF Connect.
> Added UIView Helper Methods to detect whether a view is currently part of the view hierarchy

- Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
This is helpful to track objects that we expect to be deallocated, and aren't. Or, that objects we suppose have been deallocated log when they shouldn't. You can tell we're working on memory leaks.
> NordicLog now accepts AnyObject

- Sources/iOS-Common-Libraries/Extensions/NordicLog.swift
What we need to know when logging from objects is their class name and their address, to be able to see if a different instance of said object is sending the logs. So we need to clear this out better.
> NordicLog Update to better handle UIView(s)

- Sources/iOS-Common-Libraries/Extensions/View.swift
Again, when we find something fundamental we think we're going to need to use multiple times, it goes into the common-library.
> Added "fixedListRowSeparatorPadding()" API

- Sources/iOS-Common-Libraries/Views/InlinePicker.swift
> Fix: Prioritise "CustomStringConvertible" versus "CustomDebugStringConvertible" for InlinePicker selection

- Sources/iOS-Common-Libraries/Utilities/Float.swift
If not public, can't use them as a Library API User.
> Made a couple of SFloatReserved constants public

- Sources/iOS-Common-Libraries/Utilities/Date.swift
This is a step. Because for CGMS we also need to provide timezone and DST offset.
> Added Date toData() API

- Sources/iOS-Common-Libraries/Utilities/Data.swift
Byte counts can happen a lot. Or get called a lot. This is a very minor optimisation pass, but it can't hurt. Not much, I hope.
> Minor: Reuse ByteCountFormatter

- Sources/iOS-Common-Libraries/Views/FPSCounter.swift
- Sources/iOS-Common-Libraries/Views/NoContentView.swift
Makes sense to use our own extensions.
> Internal Usage of the newly added CGSize(asSquare:) initialiser

- Sources/iOS-Common-Libraries/Views/CancellableTextField.swift
Mostly it's a bug caused by a change of focus that's not reported back to 'isEditing'.
> Fix for CancellableTextField not removing "Editing" Features with Keyboard Dismiss

- Sources/iOS-Common-Libraries/Views/CancellableTextField.swift
We don't have a good color for the Mac. I mean, when we do need one for a Mac, proper Mac not Catalyst app, I hope we can come up with one.
> Reverted to previous CancellableTextField Background Color for iOS / Catalyst

- Sources/iOS-Common-Libraries/Parsers/DataParser.swift
This is, so that we can use a custom View that nRF Connect uses in Common, so it's useable in other apps. But it has this "plumbing" component, which we want to keep extensible and private at the moment. Not really sure about what's the best way to go around that, unfortunately.
> Ported a modified version of nRF Connect's "DataParser"

- Sources/iOS-Common-Libraries/Parsers/CommonDataParser+Foundation.swift
- Sources/iOS-Common-Libraries/Parsers/CommonDataParser.swift
- Sources/iOS-Common-Libraries/Parsers/NordicDataParser.swift
So now a "user" of this library can adopt this API, rather than having to base itself on it. We also defined a library type to cover the cases we need to use from the NordicDataField we want to port.
> Refactored DataParser into "NordicDataParser" + "CommonDataParser"

- Sources/iOS-Common-Libraries/Parsers/NordicDataParser.swift
At least, that was the original intention.
> Fix: NordicDataParser's isValid() API should be public

- Sources/iOS-Common-Libraries/Parsers/NordicDataParser.swift
A few characters less, and also easier on the mind.
> Renamed AcceptedByteCount "greaterThan" to "moreThan"

- Sources/iOS-Common-Libraries/Parsers/Glucose/RecordOpcode.swift
It's not prefixed with "Glucose" because I think it can be, or it is used, for other services.
> Added (Glucose) RACP Record Access Point Opcode(s)

- Sources/iOS-Common-Libraries/Views/DevZoneLinkView.swift
Because, we need the same thing in two apps. So...
> Added DevZoneLinkView

- Sources/iOS-Common-Libraries/Parsers/GlucoseMeasurement.swift
nRF Connect attempts to parse anything as Data. So, bad "Data" might be given to parse, so we must be defensive and not think that just because we're getting called, we're going to get valid Data to parse. The goal is to not crash, and if gibberish is what we get, gibberish is what should go out. But no crashing.
This won't be the last of it, of course.
> Defense against GlucoseMeasurement Data Parsing Crash
